$ErrorActionPreference = "Stop"
git fetch --tags
if (-not (git tag --list 'compat/goauth/v0.1.0')) { git tag -a 'compat/goauth/v0.1.0' -m 'release compat/goauth/v0.1.0' }
if (-not (git tag --list 'compat/gocircuit/v0.1.0')) { git tag -a 'compat/gocircuit/v0.1.0' -m 'release compat/gocircuit/v0.1.0' }
if (-not (git tag --list 'compat/goerror/v0.1.0')) { git tag -a 'compat/goerror/v0.1.0' -m 'release compat/goerror/v0.1.0' }
if (-not (git tag --list 'compat/gologger/v0.1.0')) { git tag -a 'compat/gologger/v0.1.0' -m 'release compat/gologger/v0.1.0' }
if (-not (git tag --list 'compat/gometrics/v0.1.0')) { git tag -a 'compat/gometrics/v0.1.0' -m 'release compat/gometrics/v0.1.0' }
if (-not (git tag --list 'compat/goratelimit/v0.1.0')) { git tag -a 'compat/goratelimit/v0.1.0' -m 'release compat/goratelimit/v0.1.0' }
if (-not (git tag --list 'compat/goretry/v0.1.0')) { git tag -a 'compat/goretry/v0.1.0' -m 'release compat/goretry/v0.1.0' }
if (-not (git tag --list 'compat/gosanitizer/v0.1.0')) { git tag -a 'compat/gosanitizer/v0.1.0' -m 'release compat/gosanitizer/v0.1.0' }
if (-not (git tag --list 'compat/gotimeout/v0.1.0')) { git tag -a 'compat/gotimeout/v0.1.0' -m 'release compat/gotimeout/v0.1.0' }
if (-not (git tag --list 'compat/gotracing/v0.1.0')) { git tag -a 'compat/gotracing/v0.1.0' -m 'release compat/gotracing/v0.1.0' }
if (-not (git tag --list 'foundation/client/v0.1.0')) { git tag -a 'foundation/client/v0.1.0' -m 'release foundation/client/v0.1.0' }
if (-not (git tag --list 'foundation/config/v0.1.0')) { git tag -a 'foundation/config/v0.1.0' -m 'release foundation/config/v0.1.0' }
if (-not (git tag --list 'foundation/contracts/v0.1.0')) { git tag -a 'foundation/contracts/v0.1.0' -m 'release foundation/contracts/v0.1.0' }
if (-not (git tag --list 'foundation/core/v0.1.0')) { git tag -a 'foundation/core/v0.1.0' -m 'release foundation/core/v0.1.0' }
if (-not (git tag --list 'foundation/result/v0.1.0')) { git tag -a 'foundation/result/v0.1.0' -m 'release foundation/result/v0.1.0' }
if (-not (git tag --list 'foundation/runtime/v0.1.0')) { git tag -a 'foundation/runtime/v0.1.0' -m 'release foundation/runtime/v0.1.0' }
if (-not (git tag --list 'foundation/schema/v0.1.0')) { git tag -a 'foundation/schema/v0.1.0' -m 'release foundation/schema/v0.1.0' }
if (-not (git tag --list 'foundation/validator/binding/v0.1.0')) { git tag -a 'foundation/validator/binding/v0.1.0' -m 'release foundation/validator/binding/v0.1.0' }
if (-not (git tag --list 'foundation/validator/schema/v0.1.0')) { git tag -a 'foundation/validator/schema/v0.1.0' -m 'release foundation/validator/schema/v0.1.0' }
if (-not (git tag --list 'messaging/audit/v0.1.0')) { git tag -a 'messaging/audit/v0.1.0' -m 'release messaging/audit/v0.1.0' }
if (-not (git tag --list 'messaging/dlq/v0.1.0')) { git tag -a 'messaging/dlq/v0.1.0' -m 'release messaging/dlq/v0.1.0' }
if (-not (git tag --list 'messaging/example_integration/v0.1.0')) { git tag -a 'messaging/example_integration/v0.1.0' -m 'release messaging/example_integration/v0.1.0' }
if (-not (git tag --list 'messaging/idempotency/v0.1.0')) { git tag -a 'messaging/idempotency/v0.1.0' -m 'release messaging/idempotency/v0.1.0' }
if (-not (git tag --list 'messaging/inbox/v0.1.0')) { git tag -a 'messaging/inbox/v0.1.0' -m 'release messaging/inbox/v0.1.0' }
if (-not (git tag --list 'messaging/outbox/v0.1.0')) { git tag -a 'messaging/outbox/v0.1.0' -m 'release messaging/outbox/v0.1.0' }
if (-not (git tag --list 'messaging/redrive/v0.1.0')) { git tag -a 'messaging/redrive/v0.1.0' -m 'release messaging/redrive/v0.1.0' }
if (-not (git tag --list 'messaging/replay/v0.1.0')) { git tag -a 'messaging/replay/v0.1.0' -m 'release messaging/replay/v0.1.0' }
if (-not (git tag --list 'middleware/clock/v0.1.0')) { git tag -a 'middleware/clock/v0.1.0' -m 'release middleware/clock/v0.1.0' }
if (-not (git tag --list 'middleware/event/v0.1.0')) { git tag -a 'middleware/event/v0.1.0' -m 'release middleware/event/v0.1.0' }
if (-not (git tag --list 'middleware/ids/v0.1.0')) { git tag -a 'middleware/ids/v0.1.0' -m 'release middleware/ids/v0.1.0' }
if (-not (git tag --list 'middleware/logging/v0.1.0')) { git tag -a 'middleware/logging/v0.1.0' -m 'release middleware/logging/v0.1.0' }
if (-not (git tag --list 'middleware/pool/v0.1.0')) { git tag -a 'middleware/pool/v0.1.0' -m 'release middleware/pool/v0.1.0' }
if (-not (git tag --list 'middleware/propagation/v0.1.0')) { git tag -a 'middleware/propagation/v0.1.0' -m 'release middleware/propagation/v0.1.0' }
if (-not (git tag --list 'middleware/registry/v0.1.0')) { git tag -a 'middleware/registry/v0.1.0' -m 'release middleware/registry/v0.1.0' }
if (-not (git tag --list 'middleware/trace/v0.1.0')) { git tag -a 'middleware/trace/v0.1.0' -m 'release middleware/trace/v0.1.0' }
if (-not (git tag --list 'observability/audit/v0.1.0')) { git tag -a 'observability/audit/v0.1.0' -m 'release observability/audit/v0.1.0' }
if (-not (git tag --list 'observability/correlation/v0.1.0')) { git tag -a 'observability/correlation/v0.1.0' -m 'release observability/correlation/v0.1.0' }
if (-not (git tag --list 'observability/v0.1.0')) { git tag -a 'observability/v0.1.0' -m 'release observability/v0.1.0' }
if (-not (git tag --list 'observability/healthcheck/v0.1.0')) { git tag -a 'observability/healthcheck/v0.1.0' -m 'release observability/healthcheck/v0.1.0' }
if (-not (git tag --list 'observability/logging/v0.1.0')) { git tag -a 'observability/logging/v0.1.0' -m 'release observability/logging/v0.1.0' }
if (-not (git tag --list 'observability/metrics/v0.1.0')) { git tag -a 'observability/metrics/v0.1.0' -m 'release observability/metrics/v0.1.0' }
if (-not (git tag --list 'observability/metrics/registry/v0.1.0')) { git tag -a 'observability/metrics/registry/v0.1.0' -m 'release observability/metrics/registry/v0.1.0' }
if (-not (git tag --list 'observability/performance/v0.1.0')) { git tag -a 'observability/performance/v0.1.0' -m 'release observability/performance/v0.1.0' }
if (-not (git tag --list 'observability/profiler/v0.1.0')) { git tag -a 'observability/profiler/v0.1.0' -m 'release observability/profiler/v0.1.0' }
if (-not (git tag --list 'observability/sentinelprofiler/v0.1.0')) { git tag -a 'observability/sentinelprofiler/v0.1.0' -m 'release observability/sentinelprofiler/v0.1.0' }
if (-not (git tag --list 'observability/span/v0.1.0')) { git tag -a 'observability/span/v0.1.0' -m 'release observability/span/v0.1.0' }
if (-not (git tag --list 'observability/telemetry/baggage/v0.1.0')) { git tag -a 'observability/telemetry/baggage/v0.1.0' -m 'release observability/telemetry/baggage/v0.1.0' }
if (-not (git tag --list 'observability/telemetry/correlation/v0.1.0')) { git tag -a 'observability/telemetry/correlation/v0.1.0' -m 'release observability/telemetry/correlation/v0.1.0' }
if (-not (git tag --list 'observability/telemetry/trace/v0.1.0')) { git tag -a 'observability/telemetry/trace/v0.1.0' -m 'release observability/telemetry/trace/v0.1.0' }
if (-not (git tag --list 'observability/tracing/v0.1.0')) { git tag -a 'observability/tracing/v0.1.0' -m 'release observability/tracing/v0.1.0' }
if (-not (git tag --list 'orchestration/di/v0.1.0')) { git tag -a 'orchestration/di/v0.1.0' -m 'release orchestration/di/v0.1.0' }
if (-not (git tag --list 'orchestration/workflow/v0.1.0')) { git tag -a 'orchestration/workflow/v0.1.0' -m 'release orchestration/workflow/v0.1.0' }
if (-not (git tag --list 'persistence/distlock/v0.1.0')) { git tag -a 'persistence/distlock/v0.1.0' -m 'release persistence/distlock/v0.1.0' }
if (-not (git tag --list 'persistence/tx/v0.1.0')) { git tag -a 'persistence/tx/v0.1.0' -m 'release persistence/tx/v0.1.0' }
if (-not (git tag --list 'persistence/uow/v0.1.0')) { git tag -a 'persistence/uow/v0.1.0' -m 'release persistence/uow/v0.1.0' }
if (-not (git tag --list 'platform/client/v0.1.0')) { git tag -a 'platform/client/v0.1.0' -m 'release platform/client/v0.1.0' }
if (-not (git tag --list 'platform/container/v0.1.0')) { git tag -a 'platform/container/v0.1.0' -m 'release platform/container/v0.1.0' }
if (-not (git tag --list 'platform/evaluator/v0.1.0')) { git tag -a 'platform/evaluator/v0.1.0' -m 'release platform/evaluator/v0.1.0' }
if (-not (git tag --list 'platform/eventbus/v0.1.0')) { git tag -a 'platform/eventbus/v0.1.0' -m 'release platform/eventbus/v0.1.0' }
if (-not (git tag --list 'platform/featureflag/v0.1.0')) { git tag -a 'platform/featureflag/v0.1.0' -m 'release platform/featureflag/v0.1.0' }
if (-not (git tag --list 'platform/servicemesh/v0.1.0')) { git tag -a 'platform/servicemesh/v0.1.0' -m 'release platform/servicemesh/v0.1.0' }
if (-not (git tag --list 'platform/versioning/v0.1.0')) { git tag -a 'platform/versioning/v0.1.0' -m 'release platform/versioning/v0.1.0' }
if (-not (git tag --list 'plugins/common/v0.1.0')) { git tag -a 'plugins/common/v0.1.0' -m 'release plugins/common/v0.1.0' }
if (-not (git tag --list 'plugins/engine/v0.1.0')) { git tag -a 'plugins/engine/v0.1.0' -m 'release plugins/engine/v0.1.0' }
if (-not (git tag --list 'plugins/v0.1.0')) { git tag -a 'plugins/v0.1.0' -m 'release plugins/v0.1.0' }
if (-not (git tag --list 'plugins/hooks/v0.1.0')) { git tag -a 'plugins/hooks/v0.1.0' -m 'release plugins/hooks/v0.1.0' }
if (-not (git tag --list 'plugins/loader/v0.1.0')) { git tag -a 'plugins/loader/v0.1.0' -m 'release plugins/loader/v0.1.0' }
if (-not (git tag --list 'plugins/manifest/v0.1.0')) { git tag -a 'plugins/manifest/v0.1.0' -m 'release plugins/manifest/v0.1.0' }
if (-not (git tag --list 'plugins/provider/v0.1.0')) { git tag -a 'plugins/provider/v0.1.0' -m 'release plugins/provider/v0.1.0' }
if (-not (git tag --list 'plugins/registry/v0.1.0')) { git tag -a 'plugins/registry/v0.1.0' -m 'release plugins/registry/v0.1.0' }
if (-not (git tag --list 'ratelimit/v1.0.0')) { git tag -a 'ratelimit/v1.0.0' -m 'release ratelimit/v1.0.0' }
if (-not (git tag --list 'resilience/adaptive_concurrency/v0.1.0')) { git tag -a 'resilience/adaptive_concurrency/v0.1.0' -m 'release resilience/adaptive_concurrency/v0.1.0' }
if (-not (git tag --list 'resilience/adaptive_retry/v0.1.0')) { git tag -a 'resilience/adaptive_retry/v0.1.0' -m 'release resilience/adaptive_retry/v0.1.0' }
if (-not (git tag --list 'resilience/backpressure/v0.1.0')) { git tag -a 'resilience/backpressure/v0.1.0' -m 'release resilience/backpressure/v0.1.0' }
if (-not (git tag --list 'resilience/batcher/v0.1.0')) { git tag -a 'resilience/batcher/v0.1.0' -m 'release resilience/batcher/v0.1.0' }
if (-not (git tag --list 'resilience/bulkhead/v0.1.0')) { git tag -a 'resilience/bulkhead/v0.1.0' -m 'release resilience/bulkhead/v0.1.0' }
if (-not (git tag --list 'resilience/cache_stampede_protection/v0.1.0')) { git tag -a 'resilience/cache_stampede_protection/v0.1.0' -m 'release resilience/cache_stampede_protection/v0.1.0' }
if (-not (git tag --list 'resilience/checkpoint/v0.1.0')) { git tag -a 'resilience/checkpoint/v0.1.0' -m 'release resilience/checkpoint/v0.1.0' }
if (-not (git tag --list 'resilience/congestion_control/v0.1.0')) { git tag -a 'resilience/congestion_control/v0.1.0' -m 'release resilience/congestion_control/v0.1.0' }
if (-not (git tag --list 'resilience/deadline/v0.1.0')) { git tag -a 'resilience/deadline/v0.1.0' -m 'release resilience/deadline/v0.1.0' }
if (-not (git tag --list 'resilience/distributed_rate_limit/v0.1.0')) { git tag -a 'resilience/distributed_rate_limit/v0.1.0' -m 'release resilience/distributed_rate_limit/v0.1.0' }
if (-not (git tag --list 'resilience/v0.1.0')) { git tag -a 'resilience/v0.1.0' -m 'release resilience/v0.1.0' }
if (-not (git tag --list 'resilience/health_supervisor/v0.1.0')) { git tag -a 'resilience/health_supervisor/v0.1.0' -m 'release resilience/health_supervisor/v0.1.0' }
if (-not (git tag --list 'resilience/hedged_request/v0.1.0')) { git tag -a 'resilience/hedged_request/v0.1.0' -m 'release resilience/hedged_request/v0.1.0' }
if (-not (git tag --list 'resilience/limiter/v0.1.0')) { git tag -a 'resilience/limiter/v0.1.0' -m 'release resilience/limiter/v0.1.0' }
if (-not (git tag --list 'resilience/load_shedder/v0.1.0')) { git tag -a 'resilience/load_shedder/v0.1.0' -m 'release resilience/load_shedder/v0.1.0' }
if (-not (git tag --list 'resilience/priority_queue/v0.1.0')) { git tag -a 'resilience/priority_queue/v0.1.0' -m 'release resilience/priority_queue/v0.1.0' }
if (-not (git tag --list 'resilience/quorum/v0.1.0')) { git tag -a 'resilience/quorum/v0.1.0' -m 'release resilience/quorum/v0.1.0' }
if (-not (git tag --list 'resilience/request_coalescing/v0.1.0')) { git tag -a 'resilience/request_coalescing/v0.1.0' -m 'release resilience/request_coalescing/v0.1.0' }
if (-not (git tag --list 'resilience/retry_backoff/v0.1.0')) { git tag -a 'resilience/retry_backoff/v0.1.0' -m 'release resilience/retry_backoff/v0.1.0' }
if (-not (git tag --list 'resilience/shadow_traffic/v0.1.0')) { git tag -a 'resilience/shadow_traffic/v0.1.0' -m 'release resilience/shadow_traffic/v0.1.0' }
if (-not (git tag --list 'resilience/state_synchronizer/v0.1.0')) { git tag -a 'resilience/state_synchronizer/v0.1.0' -m 'release resilience/state_synchronizer/v0.1.0' }
if (-not (git tag --list 'resilience/token_bucket/v0.1.0')) { git tag -a 'resilience/token_bucket/v0.1.0' -m 'release resilience/token_bucket/v0.1.0' }
if (-not (git tag --list 'resilience/traffic_mirroring/v0.1.0')) { git tag -a 'resilience/traffic_mirroring/v0.1.0' -m 'release resilience/traffic_mirroring/v0.1.0' }
if (-not (git tag --list 'resilience/validator/v0.1.0')) { git tag -a 'resilience/validator/v0.1.0' -m 'release resilience/validator/v0.1.0' }
if (-not (git tag --list 'resilience/workqueue/v0.1.0')) { git tag -a 'resilience/workqueue/v0.1.0' -m 'release resilience/workqueue/v0.1.0' }
if (-not (git tag --list 'security/v1.0.0')) { git tag -a 'security/v1.0.0' -m 'release security/v1.0.0' }
if (-not (git tag --list 'tools/lib_word/v0.1.0')) { git tag -a 'tools/lib_word/v0.1.0' -m 'release tools/lib_word/v0.1.0' }
git push origin --tags
